CREATE DATABASE IF NOT EXISTS world;
USE world;

DROP TABLE IF EXISTS city;
CREATE TABLE city (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    countrycode CHAR(3) NOT NULL,
    district VARCHAR(255) NOT NULL,
    population INT NOT NULL
);
